### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by gitonio** [truffle-box/react-box#1]
FAIL  src/App.test.js
  ● Test suite failed to run

    ENOENT: no such file or directory, stat '/home/vagrant/DAPPS/react-demo/truffle-box-react/\config\polyfills.js'
        at Error (native)

      at Object.fs.statSync (fs.js:987:18)
      at Object.statSync (node_modules/graceful-fs/polyfills.js:297:22)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        4.799s
Ran all test suites related to changed files.

Watch Usage
 › Press a to run all tests.
 › Press o to only run tests related to changed files.
 › Press p to filter by a filename regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
vagrant@vagrant-ubuntu-trusty-64:~/DAPPS/react-demo/truffle-box-react$

**Comment by DiscRiskandBisque** [comment]
@gitonio Fixed! The latest box you should be good to go. If you've already started and project with this box you can upgrade Jest to 18.1.0 and replace the "jest" part of package.json with what's in the the latest master.

Going to close this for now, but please re-open if needed!
