### ISSUE TITLE
Unhandled Rejection (TypeError): Cannot read property '<contract method>' of null

### ISSUE THREAD

**Issue by eunnovax** [truffle-box/react-box#103]
Hey Truffle team,

Please help to instantiate the contract before it is called within react component methods. Currently, contract is NOT instantiated before it is called. I'm receiving the above error while trying to call contract method. 
The error basically means React custom methods inside render() function are called BEFORE contract is instantiated.

**Comment by gitackt** [comment]
ComponentDidMount is after render() lifecycle, so you can instantiate in before render() lifecycle method. Like constructor or unsafe_componentWillMount.
But,unsafe_componentWillMount is not good solution
https://ja.reactjs.org/docs/react-component.html
