### ISSUE TITLE
1000 Dependencies with High Priority

### ISSUE THREAD

**Issue by ksolo** [truffle-box/react-box#107]
After a clean unboxing, I am getting a list of vulnerabilities from the dependencies.

```
found 1071 vulnerabilities (63 low, 8 moderate, 1000 high) in 136061 scanned packages
  run `npm audit fix` to fix 1006 of them.
  65 vulnerabilities require semver-major dependency updates.
```

**Comment by tcoulter** [comment]
cc @gnidan 

As an aside, someone mentioned this as a blocker to me recently, but I don't remember where I saw it.
