### ISSUE TITLE
'truffle unbox error' not working. gives error.

### ISSUE THREAD

**Issue by CodinMaster** [truffle-box/react-box#109]
I tried to unbox react box into an empty directory using 'truffle unbox react' and got the following error:

> √ Preparing to download
> √ Downloading
> √ Cleaning up temporary files
> Setting up boxgyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\asus\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\Coding\Blockchain\Pet_Shop_reactbox\client\node_modules\scrypt
> gyp ERR! node -v v10.16.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scrypt@6.0.3 install: 'node-gyp rebuild'
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the scrypt@6.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2019-10-03T22_04_17_559Z-debug.log
> × Setting up box
> Error: Command failed: cd client && npm install
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users\asus\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack   File "<string>", line 1
> gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack                                ^
> gyp ERR! stack SyntaxError: invalid syntax
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
> gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
> gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
> gyp ERR! System Windows_NT 10.0.17134
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd D:\Coding\Blockchain\Pet_Shop_reactbox\client\node_modules\scrypt
> gyp ERR! node -v v10.16.3
> gyp ERR! node-gyp -v v3.8.0
> gyp ERR! not ok
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! scrypt@6.0.3 install: 'node-gyp rebuild'
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the scrypt@6.0.3 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\asus\AppData\Roaming\npm-cache\_logs\2019-10-03T22_04_17_559Z-debug.log
> 
>     at checkExecSyncError (child_process.js:629:11)
>     at Object.execSync (child_process.js:666:13)
>     at Object.installBoxDependencies (C:\Users\asus\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\unbox.js:107:1)
>     at Object.setUpBox (C:\Users\asus\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\lib\utils\index.js:68:1)
>     at C:\Users\asus\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:58:1
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\asus\AppData\Roaming\npm\node_modules\truffle\build\webpack:\packages\box\dist\box.js:5:42)
> Truffle v5.0.38 (core: 5.0.38)
> Node v10.16.3
> 

I tried previously mentioned solutions:

> npm install --global --production windows-build-tools
> npm install --global node-gyp

but with no success.

**Comment by eggplantzzz** [comment]
I am able to duplicate the error above when using Node 12 but not Node 10 on a mac.

**Comment by adrianmcli** [comment]
This should be fixed now.

**Comment by CodinMaster** [comment]
Yes, works fine now.
