### ISSUE TITLE
Error "This contract doesnt have an address yet" on 1st run.

### ISSUE THREAD

**Issue by Iskereat** [truffle-box/react-box#110]
<img width="1105" alt="Screen Shot 2019-10-29 at 7 15 42 PM" src="https://user-images.githubusercontent.com/54870049/67816682-22052b00-fa81-11e9-8d73-4362da8e86e1.png">

Loads up the 'Good to go!" screen for a second, then this. =(
Contract returns 0, instead of 5.

**Comment by Iskereat** [comment]
I had the Dapper extension & MetaMask installed.

Upon deactivating dapper it worked fine.

**Comment by aenhsaihan** [comment]
I think MetaMask was causing my issue as well, I just switched MetaMask's connection to the locally running network (`truffle develop`).
