### ISSUE TITLE
UNABLE TO RUN NPM START WITH TRUFFLE UNBOX REACT

### ISSUE THREAD

**Issue by Sam-Devs** [truffle-box/react-box#123]
I do have issues using truffle client-side to build full-stack DApp. Running npm start in the terminal after unboxing React returns this error below.

_> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.     

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sam\AppData\Roaming\npm-cache\_logs\2020-06-26T20_25_16_714Z-debug.log_

I have tried every means I know to fix this but to no avail. What do I do?

**Comment by shawnkd** [comment]
I have the exact same issue. This box used to work but now i am not so sure what is wrong

**Comment by Sam-Devs** [comment]
I have been able to resolve the error. You can read through this article I published in regard to this error
https://medium.com/@ayorindesam/truffle-client-how-to-fix-npm-errors-on-truffle-client-side-app-f89200cd338
