### ISSUE TITLE
truffle unbox react not working

### ISSUE THREAD

**Issue by NicholasJonesCode** [truffle-box/react-box#135]
Hey Team,

I installed the latest truffle on my computer (Artix Linux) and I tried to unbox the react template, and I got a very long string of various errors, and I cannot make sense of it. I had truffle installed before and the unbox worked just fine, not even a month ago, but now suddenly it doesn't. Could someone please take a look? Highly appreciated, thanks in advance.

Output:
https://pastebin.com/PB6CzaKR

Yes, I did unbox in an empty directory as well. I also uninstalled and reinstalled python and it still doesnt work.

**Comment by mesaque** [comment]
same problem here ... apparently no one is caring about this project anymore

**Comment by mesaque** [comment]
@NicholasJonesCode i don't know if it helps you but i could make it working in a docker container:

image: node:10.24.0-alpine3.11
apk update
apk add --no-cache python3 py3-pip git
npm install -g truffle
truffle unbox react

**Comment by NicholasJonesCode** [comment]
> @NicholasJonesCode i don't know if it helps you but i could make it working in a docker container:
> 
> image: node:10.24.0-alpine3.11
> apk update
> apk add --no-cache python3 py3-pip git
> npm install -g truffle
> truffle unbox react

@mesaque thanks man, might try this

Seems that even though there is compilation error, it is just 1 of the packages (sha3@1.2.3) failing to compile. Seems that everything else downloads as normal.

Here's what i did to make it work:

1. truffle unbox react
2. cd client
3. npm install sha3@1.2.4
4. cd .. (to go back to the main folder)
5. truffle migrate
6. cd client
7. npm run start

There is some compilation errors after this with App.js ("contract does not have address yet"). I think it has something to do with "this.setState" not working properly. I think it might be deprecated, not sure. I recommend you do something like this to structure your App.js file better:
https://github.com/TestEHMex/StarDucks/blob/master/client/src/App.js
This guy modified his to get objects from "this" instead of from the state. I do the same thing for my project.

Let me know if you have any other questions. I spent too much time on this haha

**Comment by cds-amal** [comment]
Apologies for the late reply @NicholasJonesCode and thanks for sharing your workaround. We don't normally check Truffle boxes during our normal weekly triages and perhaps we should. Sorry you didn't get timely support here.

I've wasn't able to reproduce this issue and I wonder if the dependabot PRs may have fixed it. Can you verify if it is still an issue?

**Comment by DeveloperAlly** [comment]
This issue happens because we're trying to access a file outside of the /src directory from a CRA app.
This is not supported.
I'd suggest migrating the front-end to run off next instead of create react app probably

**Comment by Siddharth-sing** [comment]
I have a solution where we don't have to downgrade the node version and `truffle-box react` will be up and running. We will go old school. 

* **Step 1** -  Clone the truffle-box/react-box repo. from [here](https://github.com/truffle-box/react-box/) to your code editor (I have used VSCode).

> Now we have to do two major things, first one is to `compile` & `migrate` the smart contracts and the next is to install the `npm` dependencies (because `npm module` doesn't go in a repo. instead `package.json` have all the dependencies required written.)
 
* **Step 2** -  Use the command `cd truffle` to go inside the truffle folder in your project structure through the command line(Terminal). Now run **`truffle develop`**, and after that run **`compile`** and **`migrate`** one by one, after all these three commands are successfully executed, exit the terminal.
* **Step 3** - Type `cd ..` to get out of the truffle folder and use `cd client` to enter inside the `client` folder, now run **`npm install`**.
* **Step 4** - All done 👌, use command **`npm start`** inside the client folder, your truffle-box + react is configured.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/72120258/223074489-ea18ccc6-1ff3-4505-901a-7258743d6c9d.png">
