### ISSUE TITLE
Cannot unbox due to node-sass download error

### ISSUE THREAD

**Issue by alexfisher** [truffle-box/react-box#14]
Trying to run "truffle unbox react" on Windows 10.  Among a number of errors/warnings is the following:

Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":...

It appears this is an invalid URL and not available on the node-sass project.

**Comment by DiscRiskandBisque** [comment]
Which versions of node, npm and truffle?

**Comment by alexfisher** [comment]
Node: 8.1.4
NPM: 5.0.3
Truffle: 3.4.4
