### ISSUE TITLE
While transaction metmask show 0 eth but address have 100 eth

### ISSUE THREAD

**Issue by dheerajpoonia29** [truffle-box/react-box#144]
Whille transaction metamask show 0 eth but in metamask it show 100 eth on address which I import from address given by truffle develop
![a](https://user-images.githubusercontent.com/33790953/122798820-a5bafd80-d2de-11eb-9108-6d4fe4eff6ee.png)
![b](https://user-images.githubusercontent.com/33790953/122798831-a94e8480-d2de-11eb-93f7-b811704902da.png)

**Comment by somewheregreeny** [comment]
same for me.. did you fix it ?

**Comment by Dam998** [comment]
that 0 is the amount to transfer, you don't need to transfer any amount (you have to pay only the gas) so it's equal to 0
