### ISSUE TITLE
Any reason why this box using 2 years old web3?

### ISSUE THREAD

**Issue by sharp2448** [truffle-box/react-box#145]
This truffle box is using "web3": "1.2.2" which is 2 years old. Any reason for that? 
Sort of makes me wonder, is this box outdated? Should I rather create my own updated one?

**Comment by JimLynchCodes** [comment]
thanks @sharp2448!

We haven't been on top of keeping all the dependencies updated, but I think we would be welcoming to a PR that updates versions... as long as the project still works! 😁

**Comment by sharp2448** [comment]
@JimLynchCodes sure, I can give a hand with version updates... I also already did some tests with the new versions...
