### ISSUE TITLE
Can't do transaction

### ISSUE THREAD

**Issue by JimLynchCodes** [truffle-box/react-box#147]
Anyone know why it won't let me send this transaction through to set the number?

The account has 100 eth so I can't figure out why it says insufficient balance... 🤔

![Screen Shot 2021-07-19 at 10 13 58 PM](https://user-images.githubusercontent.com/5354163/126251901-625261cd-5d32-4f7a-be1e-6332da659550.png)

**Comment by JimLynchCodes** [comment]
![Screen Shot 2021-07-19 at 10 13 58 PM](https://user-images.githubusercontent.com/5354163/126251954-d4a358b1-c01c-461b-a86e-eff9cfb07108.png)

**Comment by JimLynchCodes** [comment]
![Screen Shot 2021-07-19 at 10 16 39 PM](https://user-images.githubusercontent.com/5354163/126252019-922ca824-7399-49b1-9af1-7952837c4507.png)

**Comment by JimLynchCodes** [comment]
maybe a dumb question, but is that how I switch accounts? It seems like nothing on this page is clickable 🤔

Can I switch the main account so that it stops using the wrong account by default?

Metamask even says, "hey this might not be the right account to use" but doesn't give me any way to change it... I am so confused

![Screen Shot 2021-07-20 at 1 01 47 PM](https://user-images.githubusercontent.com/5354163/126365795-c6c76542-619f-4c27-a587-8001ea1de4dc.png)

**Comment by sharp2448** [comment]
@JimLynchCodes You need to switch accounts before executing a transaction.
 Click on "hamburger" icon on top right corner > you will find a list of accounts > click on each of them for details.

**Comment by sharp2448** [comment]
> Anyone know why it won't let me send this transaction through to set the number?
> 
> The account has 100 eth so I can't figure out why it says insufficient balance... thinking
> 
> ![Screen Shot 2021-07-19 at 10 13 58 PM](https://user-images.githubusercontent.com/5354163/126251901-625261cd-5d32-4f7a-be1e-6332da659550.png)

Could be a problem with the nonce number. Try going to Settings -> Advanced -> Reset account. 
More on this issue here https://blog.chronologic.network/how-to-change-and-reset-your-nonce-in-metamask-f7ca52f480e5
