### ISSUE TITLE
not all tests are passing out of the box

### ISSUE THREAD

**Issue by Jake-Gillberg** [truffle-box/react-box#16]
`npm run test` fails at scripts/test.js with the Error:

```
Test suite failed to run
SyntaxError: Identifier 'jest' has already been declared
    at Runtime._execModule (node_modules/jest-runtime/build/index.js:442:13)
          at <anonymous>
```

**Comment by erNail** [comment]
I have the same problem.

**Comment by skeebuzz** [comment]
When I try to run the tests from a fresh react-box unbox, the SimpleStorage contract doesn't deploy and I get: Error: VM Exception while processing transaction: invalid opcode. (This is against testrpc)

**Comment by skeebuzz** [comment]
Couldn't figure out why it wasn't working so I used a vanilla truffle install and combined it with an ejected create-react-app deployment (which is what it looks like the react box is is anyway).

**Comment by ryanhagerty** [comment]
I believe this is because it's trying to run the `test.js` as a test. I found this issue which clarified: https://github.com/facebookincubator/create-react-app/issues/1319

**Comment by palafoxernesto** [comment]
[This pull request solves the issue](https://github.com/truffle-box/react-box/pull/19)

**Comment by jordanglassman** [comment]
Confirmed that version bump in PR fixes, `npm install` required.

**Comment by benjaminmbrown** [comment]
Just unboxed. Ran truffle test . testItStoresAValue fails - VM exception revert. 
![screen shot 2018-06-26 at 7 48 41 pm](https://user-images.githubusercontent.com/2537589/41945215-f5504ce0-7979-11e8-9466-7dbba72aa55f.png)
