### ISSUE TITLE
getWeb3.js ethereum.enable() is deprecated

### ISSUE THREAD

**Issue by lritter79** [truffle-box/react-box#165]
getWeb3.js has "ethereum.enable()" on line 12. According to the [docs](https://docs.metamask.io/guide/ethereum-provider.html#ethereum-enable-deprecated), it is deprecated and should be replaced with"ethereum.request({ method: 'eth_requestAccounts' })"

**Comment by beakerfm** [comment]
PR opened here for the change: https://github.com/truffle-box/react-box/pull/171

**Comment by cliffoo** [comment]
Hey @lritter79, thanks for opening this issue! This is now [fixed](https://github.com/truffle-box/react-box/blob/835125f154c234360861707afee9d35fe8ef6895/client/src/contexts/EthContext/EthProvider.jsx#L13) in the latest version.
