### ISSUE TITLE
Error: ENOENT: no such file or directory, stat './migrations'

### ISSUE THREAD

**Issue by AriHietamaki** [truffle-box/react-box#17]
Windows 10. 
NPM 3.10.10
Truffle v3.4.6 (core: 3.4.6)
Solidity v0.4.13 (solc-js)

When trying to run `truffle migrate` throws error:
```
Using network 'development'.

Error: ENOENT: no such file or directory, stat './migrations'
    at Error (native)
```

I removed row `migrations_directory: "./migrations"` from truffle.js and after that runs through.

**Comment by emazurek** [comment]
This just happened to me; just wanted to leave a note, make sure you call `truffle migrate` from root of truffle project directory.
