### ISSUE TITLE
Migration files removed

### ISSUE THREAD

**Issue by ayub-eth** [truffle-box/react-box#174]
I see the migration files have been removed;
and also the structure?
Can I check why as now when unboxing there is no migration file and need to be added manually..

**Comment by cliffoo** [comment]
The migration file you get upon `truffle init` is more of a placeholder, the current convention is that we don't use it. Feel free to add it if it fits your use case though.
As for the structure, the truffle project has moved from the root level to a `/truffle` directory for better separation of concerns.
