### ISSUE TITLE
contract deployment errors when using express server

### ISSUE THREAD

**Issue by armova** [truffle-box/react-box#18]
I am running my project successfully with contracts deployed to a local testrpc using 
```
truffle compile
truffle migrate
npm run start
```
Then when I do `npm run build` and set up my express server to load index.html from build_webpack the app loads and throws this error:

_Uncaught (in promise) Error: Token has not been deployed to detected network (network/artifact mismatch)_

The contracts are deployed and the web3 httpProvider is connecting correctly to my local testRPC. Everything runs perfectly when doing npm run start and not serving from express.

Will appreciate any help.

**Comment by Jacke** [comment]
Same 👍

**Comment by vinodrajendran001** [comment]
same issue here

**Comment by williamluke4** [comment]
Same, anyone got any pointers?

**Comment by kunalsharma** [comment]
Any solution on this issue
