### ISSUE TITLE
bug: tailwind css not working

### ISSUE THREAD

**Issue by akhileshthite** [truffle-box/react-box#194]
TailwindCSS react installation does not work with the react truffle box.

https://tailwindcss.com/docs/guides/create-react-app

**Comment by cliffoo** [comment]
Hey @akhileshthite, this box recently moved to using webpack + babel and not create-react-app anymore. Please refer to tailwind's [guide for using postcss](https://tailwindcss.com/docs/installation/using-postcss) to add tailwind to this box. Thanks!
