### ISSUE TITLE
Difference between Metamask Enabled and Disabled

### ISSUE THREAD

**Issue by vertangelx** [truffle-box/react-box#29]
I ran the example with Metamask disabled and the stored value is correctly shown as `5`.

However when I enable the Metamask plugin in Chrome, the Metamask window appears asking for the transaction to be approved, before the `SimpleStorage` method `set` is called.

    simpleStorageInstance.set(5, {from: accounts[0]})

Can someone please explain why the transaction is automatically approved/signed when Metamask is disabled, but not when Metamask is enabled?

**Comment by stephledev** [comment]
This is obviously a security feature of MetaMask. Just imagine if they didn't ask for approval. Some malicious dApp could easily steal all your coins with a simple transaction. If no injected web3 library is detected in the browser, truffle will load a web3 library on its own and by default connect to the localhost. Depending on your local client (e.g. `testrpc`), transaction calls will be automatically signed.

**Comment by matt1hong** [comment]
What is this transaction, by the way? And where do I find the code creating this transaction?
