### ISSUE TITLE
stored default value is 0 not 5 as expected

### ISSUE THREAD

**Issue by varvarasd** [truffle-box/react-box#33]
Please note I've made no modifications.
I've only followed the first 5 points in  your Installation guide
![trufflebox](https://user-images.githubusercontent.com/21359557/33899521-ab56f2d4-df63-11e7-9c47-b32ab1278595.PNG)

**Comment by Squall949** [comment]
I found out it was caused by the chrome extension of MetaMask, which resulted in getting wrong network_id. 

After I disabled the extension, the page works as expected.

**Comment by ToJen** [comment]
Note that the app tries to connect to MetaMask and if it does not find a connection, it will create a connection to 127.0.0.1:**9545** (line 24 of `src/utils/getWeb3.js`). So your `truffle.js` should look like this:

```javascript
module.exports = {
  // See <http://truffleframework.com/docs/advanced/configuration>
  // to customize your Truffle configuration!
  networks: {
  	development: {
  		host: "localhost",
  		port: 9545,
  		network_id: "*",
  		gas: 4700000
  	}
  }
};
```

Then when you run TestRPC it should be run as `testrpc -p 9545`.

Hope that helps!

**Comment by matt1hong** [comment]
Also, you should have gotten a 12-word mnemonic after you run `truffle develop`. 

First, set up your MetaMask network as in the link @Squall949 posted, then click Logout, and log back in with that mnemonic & whatever password you want.

**Comment by ahmed-belhadj** [comment]
Tried everything above, uninstalled and reinstalled everything and 0 still doesn't change to 5

**Comment by picozzimichele** [comment]
Maybe this has already been closed however:

- Change the network in Metamask and connect to the local one (I am assuming local 8545), this worked for me.
- To change network just select it from the dropdown in Metamask
