### ISSUE TITLE
Command 'truffle unbox react' not working. 

### ISSUE THREAD

**Issue by matheusml** [truffle-box/react-box#38]
With:
- Linux Fedora 27
- Node 8.9.4
- Truffle 4.0.4

And these commands:
```
mkdir truffle-box-example
cd truffle-box-example
truffle unbox react
```

I got this weird error:

```
vjE0FxA= but got sha512-ijDLlyQ7s6x1JgCLur53osjm/UXUYD9+0PbYKrBsYisYXzCxN+HC3mYDNy/dWdmf3AwqwU3CXwDCvsNgGK1S0w==. (2069 bytes)
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
make: g++: Command not found
make: *** [keccak.target.mk:113: Release/obj.target/keccak/src/addon.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mlima/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.11-300.fc27.x86_64
gyp ERR! command "/home/mlima/.nvm/versions/node/v8.9.4/bin/node" "/home/mlima/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mlima/Projects/truffle-box-example/node_modules/keccak
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keccak@1.4.0 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keccak@1.4.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mlima/.npm/_logs/2018-01-10T18_41_44_213Z-debug.log
make: g++: Command not found
make: *** [copied_files.target.mk:22: Release/obj.target/copied_files.node] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mlima/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.14.11-300.fc27.x86_64
gyp ERR! command "/home/mlima/.nvm/versions/node/v8.9.4/bin/node" "/home/mlima/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/mlima/Projects/truffle-box-example/node_modules/scrypt
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN The package dotenv is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mlima/.npm/_logs/2018-01-10T18_41_47_599Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

Any ideas?

**Comment by balibou** [comment]
<img width="626" alt="screen shot 2018-01-14 at 20 25 24" src="https://user-images.githubusercontent.com/7440159/34919806-1c70e26c-f969-11e7-893b-ef985f3f2bf3.png">

@matheusml Did you try running npm install ?

**Comment by matheusml** [comment]
@balibou I made an empty folder:

```mkdir truffle-box-example```

There's no package.json on it.

And then I run `truffle-unbox-react`

It's not possible to run `npm install` on the empty folder.

**Comment by omkarkhair** [comment]
I have the exact same error on a x64 Windows.

**Comment by yyssjj33** [comment]
same here on Mac

**Comment by karadikid** [comment]
Truffle unbox drizzle fails.  Issue:

`56619 verbose pkgid scrypt@6.0.3
56620 verbose cwd /Users/karadi/Developer/drizzle/app
56621 verbose Darwin 18.6.0
56622 verbose argv "/Users/karadi/.nvm/versions/node/v10.16.0/bin/node" "/Users/karadi/.nvm/versions/node/v10.16.0/bin/npm" "install"
56623 verbose node v10.16.0
56624 verbose npm  v6.9.0
56625 error code ELIFECYCLE
56626 error errno 1
56627 error scrypt@6.0.3 install: `node-gyp rebuild`
56627 error Exit status 1
56628 error Failed at the scrypt@6.0.3 install script.
56628 error This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by Siddharth-sing** [comment]
For Windows 

I have a solution where we don't have to downgrade the node version and `truffle-box react` will be up and running. We will go old school. 

* **Step 1** -  Clone the truffle-box/react-box repo. from [here](https://github.com/truffle-box/react-box/) to your code editor (I have used VSCode).

> Now we have to do two major things, first one is to `compile` & `migrate` the smart contracts and the next is to install the `npm` dependencies (because `npm module` doesn't go in a repo. instead `package.json` have all the dependencies required written.)
 
* **Step 2** -  Use the command `cd truffle` to go inside the truffle folder in your project structure through the command line(Terminal). Now run **`truffle develop`**, and after that run **`compile`** and **`migrate`** one by one, after all these three commands are successfully executed, exit the terminal.
* **Step 3** - Type `cd ..` to get out of the truffle folder and use `cd client` to enter inside the `client` folder, now run **`npm install`**.
* **Step 4** - All done 👌, use command **`npm start`** inside the client folder, your truffle-box + react is configured.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/72120258/223074489-ea18ccc6-1ff3-4505-901a-7258743d6c9d.png">
