### ISSUE TITLE
Issue when using 'truffle unbox react'

### ISSUE THREAD

**Issue by psa95** [truffle-box/react-box#43]
I have run the "truffle unbox react" command in PowerShell on **2 independent systems**, and both return the following error. Not too sure what needs to be done in such a situation.

<img width="671" alt="error 2" src="https://user-images.githubusercontent.com/20689830/35476329-83d91254-03c7-11e8-9fe7-84fbafea23ed.png">

**Comment by psa95** [comment]
Yeah I tried to update to the latest node and npm, still doesn't work.

**Comment by robki** [comment]
Same isue as @psa95 
Fixed it with upgrading node to v9.8.0 from v8.6.0

**Comment by mokeychan** [comment]
Emmm..l updated to the latest node and npm,nothing.lt is too much trouble for me.Try again.

**Comment by mokeychan** [comment]
OK! I forgot to say that l have solved this problem.l reinstalled VS2015(c++ desktop develop lib/windows10 sdk) 、nodejs8.11.2 、git 、windows-build-tools and it worked..l think the problem mainly at VS2015.
