### ISSUE TITLE
npm start right after unboxing fails to compile

### ISSUE THREAD

**Issue by woniesong92** [truffle-box/react-box#44]
With the following error:

```
Failed to compile.

Error in ./src/App.js
Module not found: ../build/contracts/SimpleStorage.json in /proj/src

 @ ./src/App.js 14:21-69
```

**Comment by JayLance** [comment]
try **truffle compile** then building

**Comment by dlsso** [comment]
> try **truffle compile** then building

This is the solution. Maybe it would be good to change the client readme to something more like the readme for this repo. As of right now there's no way for people to know `truffle compile` is needed just by running `truffle unbox react`, they would have to come and read this repo's readme.
