### ISSUE TITLE
Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by mokeychan** [truffle-box/react-box#56]
I got this error when l download the react-box.How to solve it? plz.
`truffle unbox react`
Downloading...
Unpacking...
Setting up...
Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)

**Comment by mokeychan** [comment]
ok,l try again and finally solved it.It really strange...
In fact, this problem has been plagued for a long time. I am not quite sure what the cause is.
But one thing that may be sure is that the name of the folder should not be as long as possible and should not named with symbol, so that you can ensure success.(It sounds a bit unbelievable, but in fact I did..)

**Comment by licklake** [comment]
I got the same problem. Reproduced on Win10.

**Comment by roma-glushko** [comment]
@licklake @mokeychan this is doesn't work actually for me. 

The directory names were webpack and w and full path /dapp/webpack and /dapp/w. I can not even come to shorten ones 😄 So this is not working for my case. Working in docker container with local installation of truffle of following version:

Truffle v4.1.13 (core: 4.1.13)
Solidity v0.4.24 (solc-js)

I have got actually the same issue as @mokeychan describe in the issue description.
