### ISSUE TITLE
truffle unbox react bignumber.js  error 

### ISSUE THREAD

**Issue by mDanz** [truffle-box/react-box#62]
I experienced this error while trying to unpack the react box. Also when I try to unpack other truffle boxes. 

>truffle.cmd unbox react
Downloading...
Unpacking...
Setting up...
Error: Command failed: npm install
npm WARN deprecated ethereumjs-testrpc@2.2.7: ethereumjs-testrpc has been renamed to ganache-cli, please use this package from now on.
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t https://github.com/debris/bignumber.js.git
npm ERR!
npm ERR! fatal: unable to access 'https://github.com/debris/bignumber.js.git/': The requested URL returned error: 504
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\uaeei\AppData\Roaming\npm-cache\_logs\2018-07-10T07_34_58_374Z-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

Does someone else experience this issue or found a solution?

**Comment by drhanlau** [comment]
I solved it by manually install bignumberjs from https://github.com/MikeMcl/bignumber.js/

**Comment by obernardovieira** [comment]
Hi,
the same has @drhanlau also solved here.
But I think this should not be the solution.

**Comment by elie222** [comment]
`yarn add bignumber.js` solved this for me.

**Comment by adrianmcli** [comment]
This is pretty old, and I don't think it is a problem anymore. Will re-open if this is not the case.
