### ISSUE TITLE
Expected import directive or contract definition. pragma solidity ^0.4.24;

### ISSUE THREAD

**Issue by kongyes** [truffle-box/react-box#63]

**Comment by cctanfujun** [comment]
same problem

**Comment by adrianmcli** [comment]
I created a truffle box that is a lot more modern and well-maintained: https://github.com/adrianmcli/truffle-react

However, I also just joined the Truffle team, so I will be overhauling this truffle box in the coming days/weeks. Use my personal one for now, I'll make sure there is an upgrade path for you guys in the future.

**Comment by SvenMeyer** [comment]
same problem here , the truffle box from @adrianmcli does not show that problem (which I saw for the first time)
@adrianmcli would be great if you could merge it / come up with of one solid version ;-)

**Comment by adrianmcli** [comment]
Should be fixed now!
