### ISSUE TITLE
npm run start fails to start. 

### ISSUE THREAD

**Issue by crazyrabbitLTC** [truffle-box/react-box#67]
Following the setup instructions in the readme file. 

npm run start fails to start. Returns: 
npm ERR! missing script: start

Instructions should specify that one needs to run **npm run start** from within the client directory.

**Comment by JacksonTom** [comment]
try  'cd client && npm start'    as recommanded

**Comment by sampriti111** [comment]
I also facing the same problem. i followed following steps-

1-  mkdir react
2- cd react
3- npx truffle unbox react
    √ Preparing to download
    √ Downloading
    √ Cleaning up temporary files
    × Setting up box

     Unbox successful. Sweet!
4- truffle develop
5- compile
6- migrate
7- cd client  //in another terminal
8- npm run start
 > client@0.1.0 start D:\react\client
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bandriya\AppData\Roaming\npm-cache\_logs\2019-02-24T09_41_20_222Z-debug.log

how to fix it?

**Comment by codepalmz** [comment]
Same @sampriti111 ! I currently facing that issue, I've been trying to fix it. Please were you able to find a solution?

**Comment by JsuBaron** [comment]
Have you solved that issue? @codepalmz

**Comment by codepalmz** [comment]
No, I haven't, please do you have any solution?

**Comment by SrinathYatawar** [comment]
Hii everyone if anyone had solved the issue please help me.
