### ISSUE TITLE
stored value was not set

### ISSUE THREAD

**Issue by yuwiggin** [truffle-box/react-box#8]
tried to run this example but failed. The stored value is:  **0** (i.e. initial state) instead of **5** (a setting).

**Comment by michaltakac** [comment]
Make sure you're using ethereumjs-testrpc and not injecting web3 from another service - e.g. from Parity or MetaMask.

I had this problem too because I forgot to turn off Parity and MetaMask from Google Chrome extensions, after that the app created local web3 from testrpc and everything worked.

**Comment by DiscRiskandBisque** [comment]
@yuwiggin If you are using MetaMask, make sure it's connected to localhost:8545 (you can change networks in the upper-right dropdown). Also, use the mnemonic given by the testRPC (it outputs when you first run the testrpc) to unlock MetaMask. You can do this by locking MetaMask and selecting "I forgot my password", from there paste the mnemonic into the textarea and choose any password.

**Comment by Jake-Gillberg** [comment]
I am having a similar issue. I am connected to MetaMask via localhost with the correct mneumonic (I can see my balance).

The first transaction always fails with this error:
```
Error: LevelUpArrayAdapter named 'blocks' index out of range: index 4069194; length: 10
    at /home/dev/npm/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:97358:23
    at /home/dev/npm/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:97332:5
    at /home/dev/npm/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:97778:12
    at /home/dev/npm/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:97543:19
    at /home/dev/npm/lib/node_modules/ethereumjs-testrpc/build/cli.node.js:100234:7
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Which I'm guessing is a weird metamask error where it incorrectly holds the block index when switching networks.

After reloading the page, subsequent transactions appear to go through, but I still see the stored value set to 0.

**Comment by Jake-Gillberg** [comment]
@DiscRiskandBisque, Did you get the example to work with MetaMask? It appears that MetaMask and testrpc are having some troubled interactions and the transactions that I "approve" are not going through.

(I can run this example by uninstalling MetaMask and letting it fall through to localhost just fine).
