### ISSUE TITLE
TypeError: __WEBPACK_IMPORTED_MODULE_2__utils_getWeb3__.a.then is not a function

### ISSUE THREAD

**Issue by MinhoKim1018** [truffle-box/react-box#83]
hello.. i have a very very BBBig problem!

when i compile my project on this template,  i got a Error like this 
![error](https://user-images.githubusercontent.com/44925498/48302668-b447b280-e542-11e8-9202-7e35cd698ecb.png)

somebody help ..! plz

**Comment by MinhoKim1018** [comment]
I solved it!...

**Comment by FateZero666** [comment]
> I solved it!...

I have the same question as you. Could you please help me?

**Comment by MinhoKim1018** [comment]
you can choice creact-react-app Two Mode in github! master Mode and develop Mode 
so you need to download create-react-app(develop Mode).
i think you are using master mode.  
and soorry about that i dont know about master mode...
