### ISSUE TITLE
cd client and enter npm run start, but fails to start, how to fix it

### ISSUE THREAD

**Issue by AlphonseLeger** [truffle-box/react-box#98]
Why not automatically download dependency packages...
![problem](https://user-images.githubusercontent.com/43239307/54596837-6dc60f80-4a70-11e9-8283-463ffc3c8396.JPG)

**Comment by ahmed-belhadj** [comment]
Getting the same error too

**Comment by SystemStack** [comment]
I had a similar issue when I was using Node 12.1.0 on Windows10 but reverting to the LTS (10.15.3) fixed everything for me

**Comment by itzr** [comment]
I have a similar error:
- Ubuntu 18.04
- Node 10.15.3
- Npm 6.4.1

![screenshot](https://user-images.githubusercontent.com/23465548/57400656-35d08280-71fe-11e9-82ba-0c370f534d6f.png)

**Comment by urjitrajgor** [comment]
Any solution?
I am getting the same error

**Comment by itzr** [comment]
> Any solution?
> I am getting the same error

Try using yarn instead and then running "yarn react-scripts start".

That worked for me.

**Comment by AlphonseLeger** [comment]
Resolved. Dependent packages are best installed manually, should run 'npm install' before 'npm run start', and before run 'npm install', should install the Git.
